名称: 自动检查

在:
  workflow_dispatch:
  推送:
    分支: [ 主 ]
    路径忽略:
      - 'README.md'
      - 'imgs/**'
  日程表:
    - cron: '0 1,4,12 * * *'

职位:
  构建:
    名称: glados/railgun 签到
    运行于: ubuntu-latest
      
    权限:
      目录: 阅读
      操作: 写入

    策略:
      矩阵:
        python-version: [3.13]

    # 在这里添加全局环境变量，强制后续所有第三方 actions 兼容 Node.js 24 运行环境
    环境:
      强制将 JavaScript 操作转换为 Node24: true

    步骤:
    - 名称: 结账代码
      使用: actions/checkout@v6

    - 名称: 设置 Python ${{ matrix.python-version }}
      使用: actions/setup-python@v6
      与:
        python-version: ${{ matrix.python-version }}

    # 安装 python 库
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pypushdeer

    # 执行 签到脚本
    - name: Running checkin
      run: |
        python checkin.py
      env:
        PUSHDEER_SENDKEY: ${{ secrets.PUSHDEER_SENDKEY }}
        GLADOS_COOKIES: ${{ secrets.GLADOS_COOKIES }}
        GLADOS_EXCHANGE_PLAN: ${{ secrets.GLADOS_EXCHANGE_PLAN }}
        GLADOS_VERBOSE: ${{ secrets.GLADOS_VERBOSE }}

    - name: Keep alive
      uses: liskin/gh-workflow-keepalive@v1 
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 7
        delete_run_by_conclusion_pattern: success
